-- begin CEPV_POLICY
alter table CEPV_POLICY add constraint FK_CEPV_POLICY_ON_CUSTOMER foreign key (CUSTOMER_ID) references CEPV_CUSTOMER(ID)^
create index IDX_CEPV_POLICY_ON_CUSTOMER on CEPV_POLICY (CUSTOMER_ID)^
-- end CEPV_POLICY
